### ISSUE TITLE
Apostrophes and brackets cause script to fail.

### ISSUE THREAD

**Issue by cecoates** [PonyLucky/CBZ-Manga-Creator#1]
This script works great and has been really handy, thanks!

It won't run if a directory name has an apostrophe: 

`'`

And the script abruptly ends if it encounters brackets:

`[]`

I've just been renaming directories and renaming them back after. For chapter directories with brackets, it'll fail on the rename step for changing ZIP to a CBZ, so not a huge deal to do those stragglers manually. Series directories with a bracket the script will display the message that it's finished without running, however.

**Comment by PonyLucky** [comment]
So if I understand well, 

`'` aren't converted but don't cause the script to crash.

`[]` are converted but the script crashes when it encounter one during the rename part.

Thank you for the issue! I'll work on it tonight.

**Comment by PonyLucky** [comment]
![image](https://user-images.githubusercontent.com/60187395/154746103-10da78f9-fdda-42b3-bf5e-e7b2687582e6.png)

I don't see the problem with the apostrophes. If your encounter this bug again please screen the error message and the rendered folder (if there is any)

**Comment by PonyLucky** [comment]
Seems like it's okay (though I can't be sure for the apostrophes because I don't have this problem).
